### ISSUE TITLE
Fails compile with 1.3.7b

### ISSUE THREAD

**Issue by clmerriman** [Castaglia/proftpd-mod_autohost#8]
Declaration of pr_namebind_create changed between 1.3.7a and 1.3.7b:

1.3.7a
```
int pr_namebind_create(server_rec *server, const char *name,
  const pr_netaddr_t *addr, unsigned int port);
```
  

1.3.7b
```
int pr_namebind_create(server_rec *server, const char *name,
  pr_ipbind_t *ipbind, const pr_netaddr_t *addr, unsigned int port);
```

This causes make to fail:
```
mod_autohost.c: In function ‘process_serveralias’:
mod_autohost.c:138:5: warning: passing argument 3 of ‘pr_namebind_create’ from incompatible pointer type [enabled by default]
     res = pr_namebind_create(s, c->argv[0], s->addr, s->ServerPort);
     ^
In file included from ../include/conf.h:86:0,
                 from mod_autohost.c:28:
../include/bindings.h:160:5: note: expected ‘struct pr_ipbind_t *’ but argument is of type ‘const struct pr_netaddr_t *’
 int pr_namebind_create(server_rec *server, const char *name,
     ^
mod_autohost.c:138:5: warning: passing argument 4 of ‘pr_namebind_create’ makes pointer from integer without a cast [enabled by default]
     res = pr_namebind_create(s, c->argv[0], s->addr, s->ServerPort);
     ^
In file included from ../include/conf.h:86:0,
                 from mod_autohost.c:28:
../include/bindings.h:160:5: note: expected ‘const struct pr_netaddr_t *’ but argument is of type ‘unsigned int’
 int pr_namebind_create(server_rec *server, const char *name,
     ^
mod_autohost.c:138:5: error: too few arguments to function ‘pr_namebind_create’
     res = pr_namebind_create(s, c->argv[0], s->addr, s->ServerPort);
     ^
In file included from ../include/conf.h:86:0,
                 from mod_autohost.c:28:
../include/bindings.h:160:5: note: declared here
 int pr_namebind_create(server_rec *server, const char *name,
     ^
make[1]: *** [mod_autohost.o] Error 1
```
I tested with a simple configuration on Centos 7:
`./configure --enable-ipv6 --enable-openssl --with-libraries=/usr/lib64/mysql:/usr/include/openssl --with-includes=contrib/:/usr/include/openssl --with-modules=mod_autohost --prefix=/usr --sysconfdir=/etc --disable-auth-pam --disable-ident --disable-auth-file --disable-sendfile`

**Comment by Castaglia** [comment]
Doh!  I'd naively assumed that nothing else was using that function -- and broke the public API.  Fix coming up.  Thanks for catching this!

**Comment by Castaglia** [comment]
Now fixed in master.  Thanks!
